image: python:latest

services:
  - mysql:latest

before_script:
  - python -V  # Print out python version for debugging
  # Uncomment next line if your Django app needs a JS runtime:
  # - apt-get update -q && apt-get install nodejs -yqq
  - pip install -r requirements.txt


stages:
  - test
  - deploy

test:
  stage: test
  script:
    # this configures Django application to use attached postgres database that is run on `postgres` host
    - export DATABASE_URL='mysql://b84d0598f451c7:636194e5@us-cdbr-east-03.cleardb.com/heroku_a5f1d6e71ebb6f7?reconnect=true'
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install -r requirements.txt
    - python manage.py test

production:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=dispatch-planner --api-key=852df062-98ce-40a7-979e-50103f49f115
  only:
    - master